"""initial_schema

Revision ID: 54bb95643a8c
Revises: 
Create Date: 2026-04-08 14:41:39.039910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '54bb95643a8c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_runs',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column(
                        'startup_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('submitted_at', sa.DateTime(), nullable=False),
                    sa.Column('started_at', sa.DateTime(), nullable=True),
                    sa.Column('completed_at', sa.DateTime(), nullable=True),
                    sa.Column('prompt_version',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('overall_score', sa.Float(), nullable=True),
                    sa.Column('overall_confidence', sa.Float(), nullable=True),
                    sa.Column('executive_summary',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('failure_reason',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('recommendation_investors',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('investor_id', sa.String(
                        length=128), nullable=False),
                    sa.Column('profile_version',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('source_updated_at',
                              sa.DateTime(), nullable=False),
                    sa.Column('document_json', sa.Text(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_recommendation_investors_investor_id'),
                    'recommendation_investors', ['investor_id'], unique=True)
    op.create_table('recommendation_runs',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('run_id', sa.String(length=128), nullable=False),
                    sa.Column('investor_id', sa.String(
                        length=128), nullable=False),
                    sa.Column('investor_profile_version',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('candidate_count', sa.Integer(), nullable=False),
                    sa.Column('candidate_set_size',
                              sa.Integer(), nullable=False),
                    sa.Column('generated_at', sa.DateTime(), nullable=False),
                    sa.Column('document_json', sa.Text(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_recommendation_runs_investor_id'),
                    'recommendation_runs', ['investor_id'], unique=False)
    op.create_index(op.f('ix_recommendation_runs_run_id'),
                    'recommendation_runs', ['run_id'], unique=True)
    op.create_table('recommendation_startups',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('startup_id', sa.String(
                        length=128), nullable=False),
                    sa.Column('profile_version',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('source_updated_at',
                              sa.DateTime(), nullable=False),
                    sa.Column('startup_name', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('primary_industry',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('document_json', sa.Text(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_recommendation_startups_startup_id'),
                    'recommendation_startups', ['startup_id'], unique=True)
    op.create_table('webhook_deliveries',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('delivery_id', sa.String(
                        length=64), nullable=False),
                    sa.Column('evaluation_run_id',
                              sa.Integer(), nullable=False),
                    sa.Column('startup_id', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('callback_url', sa.Text(), nullable=False),
                    sa.Column('attempt', sa.Integer(), nullable=False),
                    sa.Column('response_status', sa.Integer(), nullable=False),
                    sa.Column(
                        'outcome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('response_body', sa.Text(), nullable=True),
                    sa.Column('payload_json', sa.Text(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_webhook_deliveries_delivery_id'),
                    'webhook_deliveries', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_evaluation_run_id'),
                    'webhook_deliveries', ['evaluation_run_id'], unique=False)
    op.create_table('evaluation_documents',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('evaluation_run_id',
                              sa.Integer(), nullable=False),
                    sa.Column('document_id', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('document_type',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('processing_status',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('extraction_status',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('source_file_url_or_path',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('extracted_text_path_or_blob',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('artifact_metadata_json',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('document_score', sa.Float(), nullable=True),
                    sa.Column('document_confidence',
                              sa.Float(), nullable=True),
                    sa.ForeignKeyConstraint(['evaluation_run_id'], [
                        'evaluation_runs.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('evaluation_logs',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('evaluation_run_id',
                              sa.Integer(), nullable=False),
                    sa.Column(
                        'step', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['evaluation_run_id'], [
                        'evaluation_runs.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('evaluation_criteria_results',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('evaluation_document_id',
                              sa.Integer(), nullable=False),
                    sa.Column('criterion_code',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('criterion_name',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('score', sa.Float(), nullable=True),
                    sa.Column('confidence', sa.Float(), nullable=False),
                    sa.Column(
                        'reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('evidence_refs_json',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.ForeignKeyConstraint(['evaluation_document_id'], [
                        'evaluation_documents.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluation_criteria_results')
    op.drop_table('evaluation_logs')
    op.drop_table('evaluation_documents')
    op.drop_index(op.f('ix_webhook_deliveries_evaluation_run_id'),
                  table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_delivery_id'),
                  table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_recommendation_startups_startup_id'),
                  table_name='recommendation_startups')
    op.drop_table('recommendation_startups')
    op.drop_index(op.f('ix_recommendation_runs_run_id'),
                  table_name='recommendation_runs')
    op.drop_index(op.f('ix_recommendation_runs_investor_id'),
                  table_name='recommendation_runs')
    op.drop_table('recommendation_runs')
    op.drop_index(op.f('ix_recommendation_investors_investor_id'),
                  table_name='recommendation_investors')
    op.drop_table('recommendation_investors')
    op.drop_table('evaluation_runs')
    # ### end Alembic commands ###
